-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 23:50:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appuser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appuser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appuser` DEFAULT CHARACTER SET utf8 ;
USE `appuser` ;

-- -----------------------------------------------------
-- Table `appuser`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuser`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(80) NOT NULL,
  `lastnames` VARCHAR(80) NOT NULL,
  `idu` VARCHAR(80) NOT NULL,
  `user` VARCHAR(80) NOT NULL,
  `passwd` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
